version: 2

builds:
  - id: kite
    dir: ./core
    main: .
    binary: kite
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/vladimirvivien/starkite/core/version.Version={{.Version}}
      - -X github.com/vladimirvivien/starkite/core/version.BuildTime={{.Date}}
      - -X github.com/vladimirvivien/starkite/core/version.GitCommit={{.Commit}}

  - id: kite-cloud
    dir: ./cloud
    main: .
    binary: kite-cloud
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/vladimirvivien/starkite/core/version.Version={{.Version}}
      - -X github.com/vladimirvivien/starkite/core/version.BuildTime={{.Date}}
      - -X github.com/vladimirvivien/starkite/core/version.GitCommit={{.Commit}}
      - -X github.com/vladimirvivien/starkite/core/version.Edition=cloud

  - id: kite-ai
    dir: ./ai
    main: .
    binary: kite-ai
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/vladimirvivien/starkite/core/version.Version={{.Version}}
      - -X github.com/vladimirvivien/starkite/core/version.BuildTime={{.Date}}
      - -X github.com/vladimirvivien/starkite/core/version.GitCommit={{.Commit}}
      - -X github.com/vladimirvivien/starkite/core/version.Edition=ai

archives:
  - id: kite
    ids:
      - kite
    formats:
      - binary
    name_template: "kite-{{ .Os }}-{{ .Arch }}"

  - id: kite-cloud
    ids:
      - kite-cloud
    formats:
      - binary
    name_template: "kite-cloud-{{ .Os }}-{{ .Arch }}"

  - id: kite-ai
    ids:
      - kite-ai
    formats:
      - binary
    name_template: "kite-ai-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  github:
    owner: vladimirvivien
    name: starkite
  prerelease: auto
