version: 2

builds:
  - id: basekite
    dir: ./basekite
    main: .
    binary: basekite
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/project-starkite/starkite/basekite/version.Version={{.Version}}
      - -X github.com/project-starkite/starkite/basekite/version.BuildTime={{.Date}}
      - -X github.com/project-starkite/starkite/basekite/version.GitCommit={{.Commit}}

  - id: cloudkite
    dir: ./cloudkite
    main: .
    binary: cloudkite
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/project-starkite/starkite/basekite/version.Version={{.Version}}
      - -X github.com/project-starkite/starkite/basekite/version.BuildTime={{.Date}}
      - -X github.com/project-starkite/starkite/basekite/version.GitCommit={{.Commit}}
      - -X github.com/project-starkite/starkite/basekite/version.Edition=cloud

  - id: aikite
    dir: ./aikite
    main: .
    binary: aikite
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/project-starkite/starkite/basekite/version.Version={{.Version}}
      - -X github.com/project-starkite/starkite/basekite/version.BuildTime={{.Date}}
      - -X github.com/project-starkite/starkite/basekite/version.GitCommit={{.Commit}}
      - -X github.com/project-starkite/starkite/basekite/version.Edition=ai

  - id: kite
    dir: ./allkite
    main: .
    binary: kite
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/project-starkite/starkite/basekite/version.Version={{.Version}}
      - -X github.com/project-starkite/starkite/basekite/version.BuildTime={{.Date}}
      - -X github.com/project-starkite/starkite/basekite/version.GitCommit={{.Commit}}
      - -X github.com/project-starkite/starkite/basekite/version.Edition=all

archives:
  - id: basekite
    ids:
      - basekite
    formats:
      - binary
    name_template: "basekite-{{ .Os }}-{{ .Arch }}"

  - id: cloudkite
    ids:
      - cloudkite
    formats:
      - binary
    name_template: "cloudkite-{{ .Os }}-{{ .Arch }}"

  - id: aikite
    ids:
      - aikite
    formats:
      - binary
    name_template: "aikite-{{ .Os }}-{{ .Arch }}"

  - id: kite
    ids:
      - kite
    formats:
      - binary
    name_template: "kite-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  github:
    owner: vladimirvivien
    name: starkite
  prerelease: auto
