// Command gendocs compiles Starkite's API reference tables into a Go table the
// language server links in.
//
// The reference documents are the only place parameter names are recorded, and
// they do not ship inside the binary. Generating a table keeps hover and
// signature help working for an installed kite with no docs directory on disk,
// and keeps the parse cost out of server start-up.
//
// Run from the repository root:
//
//	go run ./libkite/lsp/internal/gendocs
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strconv"

	"github.com/project-starkite/starkite/libkite/lsp/apidocs"
)

func main() {
	var (
		in  = flag.String("in", "docs/references/api", "directory of API reference markdown")
		out = flag.String("out", "libkite/lsp/apidocs/table_gen.go", "generated Go file")
	)
	flag.Parse()

	entries, err := apidocs.ParseDir(*in)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gendocs: reading %s: %v\n", *in, err)
		os.Exit(1)
	}
	if len(entries) == 0 {
		fmt.Fprintf(os.Stderr, "gendocs: no entries parsed from %s\n", *in)
		os.Exit(1)
	}

	sort.Slice(entries, func(i, j int) bool {
		a, b := entries[i], entries[j]
		if a.Module != b.Module {
			return a.Module < b.Module
		}
		if a.Receiver != b.Receiver {
			return a.Receiver < b.Receiver
		}
		return a.Name < b.Name
	})

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by libkite/lsp/internal/gendocs. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package apidocs\n\n")
	fmt.Fprintf(&buf, "// Table holds every documented call and property parsed from\n")
	fmt.Fprintf(&buf, "// docs/references/api. Regenerate with:\n")
	fmt.Fprintf(&buf, "//\n")
	fmt.Fprintf(&buf, "//\tgo run ./libkite/lsp/internal/gendocs\n")
	fmt.Fprintf(&buf, "var Table = []Entry{\n")
	for _, e := range entries {
		fmt.Fprintf(&buf, "\t{Module: %s, Receiver: %s, Name: %s, Signature: %s",
			quote(e.Module), quote(e.Receiver), quote(e.Name), quote(e.Signature))
		if len(e.Params) > 0 {
			fmt.Fprintf(&buf, ", Params: []string{")
			for i, p := range e.Params {
				if i > 0 {
					buf.WriteString(", ")
				}
				buf.WriteString(quote(p))
			}
			buf.WriteString("}")
		}
		if e.Returns != "" {
			fmt.Fprintf(&buf, ", Returns: %s", quote(e.Returns))
		}
		if e.Doc != "" {
			fmt.Fprintf(&buf, ", Doc: %s", quote(e.Doc))
		}
		if e.IsProperty {
			fmt.Fprintf(&buf, ", IsProperty: true")
		}
		buf.WriteString("},\n")
	}
	buf.WriteString("}\n")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "gendocs: formatting output: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gendocs: writing %s: %v\n", *out, err)
		os.Exit(1)
	}
	fmt.Printf("gendocs: wrote %d entries to %s\n", len(entries), *out)
}

func quote(s string) string { return strconv.Quote(s) }
